invalid_request:
  code: 1000
  localization:
    en: "The request is invalid Please try again"
    th: "การร้องขอข้อมูลผิด กรุณาลองใหม่อีกครั้ง"

file_not_found:
  code: 1001
  localization:
    en: "File not found. Please try again"
    th: "ไม่พบไฟล์ในระบบ กรุณาลองใหม่อีกครั้ง"

invalid_token:
  code: 1002
  localization:
    en: "Sorry invalid token. Please try again"
    th: "โทเค็นไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

json_duplicate_or_invalid_format:
  code: 1003
  localization:
    en: "Json field duplicate or invalid format. Please try again"
    th: "Json มีคีย์ซ้ำกันหรือรูปแบบฟอร์เมตผิด กรุณาลองใหม่อีกครั้ง"

invalid_email:
  code: 1004
  localization:
    en: "Email is invalid. Please try again"
    th: "รูปแบบอีเมลไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_phone_number:
  code: 1005
  localization:
    en: "Invalid phone number. Please try again"
    th: "เบอร์โทรศัพท์ไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_facebook_token:
  code: 1006
  localization:
    en: "Invalid facebook token. Please try again"
    th: "รหัสเฟสบุ๊คโทเค็นไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_google_token:
  code: 1007
  localization:
    en: "Invalid google token. Please try again"
    th: "รหัสกุเกิ้ลโทเค็นไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

otp_invalid_or_expired:
  code: 1008
  localization:
    en: "Sorry, otp invalid or expired. Please try again"
    th: "ขออภัย รหัสยืนยันไม่ถูกต้องหรือหมดอายุ กรุณาลองใหม่อีกครั้ง"

invalid_prefix_path_upload:
  code: 1009
  localization:
    en: "Prefix path for the upload file is invalid. Please try again"
    th: "พาร์ทไฟล์สำหรับอัพโหลดไฟล์ไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_maximum_size:
  code: 1010
  localization:
    en: "File upload have a maximum limit. Please try again"
    th: "ไฟล์ที่อัพโหลด มีขนาดเกินกำหนด กรุณาลองใหม่อีกครั้ง"

invalid_type_image_file:
  code: 1011
  localization:
    en: "Sorry, can't to upload file because type file not type image"
    th: "ขออภัย ไม่สามารถอัพโหลดไฟล์ได้ เนื่องจากไฟล์ไม่ใช่รูปภาพ"

email_already_exists:
  code: 1012
  localization:
    en: "This email already exists. Please try again"
    th: "มีอีเมลนี้อยู่ในระบบอยู่แล้ว กรุณาลองใหม่อีกครั้ง"

phone_number_already_exists:
  code: 1013
  localization:
    en: "This phoneNumber already exists. Please try again"
    th: "มีเบอร์นี้อยู่ในระบบอยู่แล้ว กรุณาลองใหม่อีกครั้ง"

invalid_name:
  code: 1014
  localization:
    en: "Please enter name."
    th: "กรุณากรอกชื่อ"

invalid_password:
  code: 1015
  localization:
    en: "Sorry, your password is incorrect. Please try again"
    th: "ขออภัย รหัสผ่านของคุณไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_amount_password:
  code: 1016
  localization:
    en: "Sorry, password must be at less 6 characters. Please try again"
    th: "ขออภัย รหัสผ่านของคุณต้องมีอย่างน้อย 6 อักขระขึ้นไป กรุณาลองใหม่อีกครั้ง"

invalid_email_not_already_exists:
  code: 1017
  localization:
    en: "This email not already exists in system. Please try again"
    th: "ขออภัย อีเมลของคุณไม่มีอยู่ในระบบ กรุณาลองใหม่อีกครั้ง"

invalid_token_not_expire:
  code: 1018
  localization:
    en: "Sorry, this your token not expire time. Please try again"
    th: "ขออภัย รหัสโทเค็นนี้ของคุณยังไม่หมดอายุ กรุณาลองใหม่อีกครั้ง"

invalid_date_time:
  code: 1019
  localization:
    en: "Sorry, datetime is invalid format, Please try again."
    th: "ขออภัย วันเวลาที่คุณส่งมีรูปแบบไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_size_file:
  code: 1020
  localization:
    en: "File upload invalid size. Please try again"
    th: "ไฟล์ที่อัพโหลด มีขนาดไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_amount_file:
  code: 1021
  localization:
    en: "File upload more than 12 file. Please try again"
    th: "จำนวนไฟล์ในการอัพโหลดมีมากกว่า 12 ไฟล์ กรุณาลองใหม่อีกครั้ง"

already_tag:
  code: 1022
  localization:
    en: "Tag already exists"
    th: "แท็กนี้มีอยู่แล้ว"

invalid_apple_token:
  code: 1023
  localization:
    en: "Invalid apple token. Please try again"
    th: "รหัสแอปเปิ้ลโทเค็นไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

password_does_not_match:
  code: 1024
  localization:
    en: "Password does not match. Please try again"
    th: "รหัสผ่านและยืนยันรหัสผ่าน ไม่ตรงกัน กรุณาลองใหม่อีกครั้ง"

file_is_empty:
  code: 1025
  localization:
    en: "File is empty because key is invalid. Please try again"
    th: "ไม่พบไฟล์ที่ส่งมาเนื่องจาก key ที่ระบุมาไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_otp:
  code: 1026
  localization:
    en: "Sorry, otp invalid or expired. Please try again"
    th: "ขออภัย รหัสยืนยันไม่ถูกต้องหรือหมดอายุ กรุณาลองใหม่อีกครั้ง"

invalid_permission_role:
  code: 1027
  localization:
    en: "Sorry,Your permission cannot do the transaction. Please try again"
    th: "ขออภัย สิทธิ์ของคุณไม่สามารถทำรายการดังกล่าวได้ กรุณาลองใหม่อีกครั้ง"

invalid_current_password:
  code: 1028
  localization:
    en: "Sorry, your current password is incorrect. Please try again"
    th: "ขออภัย รหัสผ่านปัจจุบันของคุณไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

date_time_cannot_empty:
  code: 1029
  localization:
    en: "Sorry, date time is a required field"
    th: "ขออภัย กรุณาระบุข้อมูลเกี่ยวกับเวลา"

over_max_size_of_name:
  code: 1030
  localization:
    en: "Sorry, name cannot exceed 50 characters"
    th: "ขออภัย ชื่อไม่สามารถกรอกเกิน 50 อักขระได้"

# These are what we response to our internal services
internal:
  success:
    code: 0
    localization:
      en: "Success"
      th: "สำเร็จ"

  bad_request:
    code: 400
    localization:
      en: "System cannot process this request at the moment. Please try again later"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  connection_error:
    code: 500
    localization:
      en: "Connection error. Please try again"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  database_not_found:
    code: 404
    localization:
      en: "Database not found. Please try again"
      th: "ขออภัย ไม่พบข้อมูลในระบบ กรุณาลองใหม่อีกครั้ง"

  unauthorized:
    code: 401
    localization:
      en: "this request at the moment. Please try again later"
      th: "ขออภัย ระบบไม่อนุญาตให้คุณเข้าถึงการร้องขอได้ กรุณาลองใหม่อีกครั้ง"